2024-09-18 22:32:30,883 | WARNING | Неверный тип данных для объекта Runner
Traceback (most recent call last):
  File "C:\Users\Admin\Desktop\module\pythonProject1\module 12_ПОДДЕРЖКА ЦИКЛА РАЗРАБОТКИ\logging_12_4\tests_12_4.py", line 27, in test_run
    runner = Runner(15, 5)
             ^^^^^^^^^^^^^
  File "C:\Users\Admin\Desktop\module\pythonProject1\module 12_ПОДДЕРЖКА ЦИКЛА РАЗРАБОТКИ\logging_12_4\runner_tournament.py", line 6, in __init__
    raise TypeError(f'Имя может быть только строкой, передано {type(name).__name__}')
TypeError: Имя может быть только строкой, передано int
2024-09-18 22:32:30,886 | WARNING | Неверная скорость для Runner
Traceback (most recent call last):
  File "C:\Users\Admin\Desktop\module\pythonProject1\module 12_ПОДДЕРЖКА ЦИКЛА РАЗРАБОТКИ\logging_12_4\tests_12_4.py", line 16, in test_walk
    runner = Runner('Вася', -10)
             ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Admin\Desktop\module\pythonProject1\module 12_ПОДДЕРЖКА ЦИКЛА РАЗРАБОТКИ\logging_12_4\runner_tournament.py", line 11, in __init__
    raise ValueError(f'Скорость не может быть отрицательной, сейчас {speed}')
ValueError: Скорость не может быть отрицательной, сейчас -10
